#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 06 02:32:08 CEST 2025
# SW Build 6060944 on Thu Mar 06 19:10:09 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_filtro_fir_behav -key {Behavioral:sim_1:Functional:tb_filtro_fir} -tclbatch tb_filtro_fir.tcl -log simulate.log"
xsim tb_filtro_fir_behav -key {Behavioral:sim_1:Functional:tb_filtro_fir} -tclbatch tb_filtro_fir.tcl -log simulate.log

